//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
   // this is auto generated from database which we had linked through entity framework  //
    public partial class Employee
    {
        public int EmployeeID { get; set; }
       [Required(ErrorMessage = "this field is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "this field is required")]
        public string Position { get; set; }
        
        public string Office { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
